"""add coverage_financials collected from EDGAR

Revision ID: cb97e84ddbfe
Revises: b78ab3e25a4a
Create Date: 2026-09-11 00:41:12.327153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb97e84ddbfe'
down_revision: Union[str, Sequence[str], None] = 'b78ab3e25a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=128), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=28, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.Column('accn', sa.String(length=32), nullable=False),
    sa.Column('filed', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_start IS NULL OR period_start <= period_end', name='ck_coverage_financials_period_order'),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coverage_id', 'concept', 'period_end', name='uq_coverage_financials_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverage_financials')
    # ### end Alembic commands ###
